=== gitGNU/gnu_dataexplorer/UltramatUDP/src/resource/UltraDuoPlus_V02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Winfried BrÃ¼gmann (IBM DEUTSCHLAND) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="UltraDuoPlusSetup">
		<xs:annotation>
			<xs:documentation>Ultra Duo Plus Setup</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ChannelBaseData" type="xs:string"/>
				<xs:element name="ChannelData1" type="xs:byte"/>
				<xs:element name="ChannelData2" type="xs:byte"/>
				<xs:element name="Memory" type="MemoryType" minOccurs="40" maxOccurs="40"/>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="MemoryType">
		<xs:sequence>
			<xs:element name="TraceData" type="xs:string"/>
			<xs:element name="BatteryData" type="xs:string"/>
			<xs:element name="StepChargeData" type="xs:string"/>
			<xs:element name="CycleData" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="Name" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== gitGNU/gnu_dataexplorer/UltramatUDP/src/resource/UltraDuoPlus_Name.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 sp1 (http://www.altova.com)-->
<UltraDuoPlusSetup xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="UltraDuoPlus_V02.xsd" Name="String">
	<ChannelBaseData>String</ChannelBaseData>
	<ChannelData1>127</ChannelData1>
	<ChannelData2>127</ChannelData2>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
	<Memory Name="String">
		<TraceData>String</TraceData>
		<BatteryData>String</BatteryData>
		<StepChargeData>String</StepChargeData>
		<CycleData>String</CycleData>
	</Memory>
</UltraDuoPlusSetup>
