=== gitGNU/gnu_dataexplorer/DataExplorer/src/resource/DataExplorerFileFormat_V02.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- *************************************************************************************  	This file is part of GNU DataExplorer.    GNU DataExplorer is free software: you can redistribute it and/or modify    it under the terms of the GNU General Public License as published by    the Free Software Foundation, either version 3 of the License, or    (at your option) any later version.    GNU DataExplorer is distributed in the hope that it will be useful,    but WITHOUT ANY WARRANTY; without even the implied warranty of    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    GNU General Public License for more details.    You should have received a copy of the GNU General Public License    along with GNU DataExplorer.  If not, see <http://www.gnu.org/licenses/>.        Copyright (c) 2008,2009,2010,2011,2012,2013,2014 Winfried Bruegmann************************************************************************************** --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">	<xs:element name="DataExplorerFileFormat" type="DataExplorerFileFormatType">		<xs:annotation>			<xs:documentation>DataExplorer Data (OSD) File Structure</xs:documentation>		</xs:annotation>	</xs:element>	<xs:complexType name="RecordSetDescriptionType">		<xs:sequence>			<xs:element name="RecordSetName" type="xs:string"/>			<xs:element name="Channel_Configuration" type="xs:string"/>			<xs:element name="RecordSetComment" type="xs:string" minOccurs="0"/>			<xs:element name="RecordSetProperties" type="RecordSetPropertiesType"/>			<xs:element name="RecordProperties" type="RecordPropertiesType" maxOccurs="unbounded"/>			<xs:element name="RecordDataSize" type="xs:long">				<xs:annotation>					<xs:documentation>Number of data points</xs:documentation>				</xs:annotation>			</xs:element>			<xs:element name="RecordDataPointer" type="xs:long">				<xs:annotation>					<xs:documentation>Pointer is offset from beginniing to enable asynchronous read</xs:documentation>				</xs:annotation>			</xs:element>		</xs:sequence>	</xs:complexType>	<xs:complexType name="DataExplorerFileFormatType">		<xs:sequence>			<xs:element name="VersionStamp" type="xs:string"/>			<xs:element name="CreationStamp" type="xs:dateTime"/>			<xs:element name="FileComment" type="xs:string" minOccurs="0"/>			<xs:element name="DeviceName" type="xs:string"/>			<xs:element name="NumberOfRecordSets" type="xs:integer"/>			<xs:element name="ObjectKey" type="xs:string" minOccurs="0"/>			<xs:element name="RecordSetDescription" type="RecordSetDescriptionType" maxOccurs="unbounded"/>			<xs:element name="RecordSetDataPoints" maxOccurs="unbounded">				<xs:complexType>					<xs:sequence>						<xs:element name="RecordDataArray" type="xs:hexBinary" maxOccurs="unbounded"/>					</xs:sequence>				</xs:complexType>			</xs:element>		</xs:sequence>	</xs:complexType>	<xs:complexType name="ColorType">		<xs:sequence>			<xs:element name="Red" type="xs:integer"/>			<xs:element name="Green" type="xs:integer"/>			<xs:element name="Blue" type="xs:integer"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="MeasurementType">		<xs:sequence>			<xs:element name="name" type="xs:string"/>			<xs:element name="symbol" type="xs:string"/>			<xs:element name="unit" type="xs:string"/>			<xs:element name="active" type="xs:boolean" nillable="false" minOccurs="0">				<xs:annotation>					<xs:documentation>true can read data, false inactive, null -> calculation = true</xs:documentation>				</xs:annotation>			</xs:element>			<xs:element name="Property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="PropertyType">		<xs:attribute name="name" type="xs:string" use="required"/>		<xs:attribute name="value" use="required"/>		<xs:attribute name="type" type="data_types" use="required"/>		<xs:attribute name="description" type="xs:string"/>	</xs:complexType>	<xs:simpleType name="data_types">		<xs:restriction base="xs:string">			<xs:enumeration value="Integer"/>			<xs:enumeration value="Double"/>			<xs:enumeration value="Boolean"/>			<xs:enumeration value="String"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="line_style_type">		<xs:restriction base="xs:string">			<xs:enumeration value="LINE_SOLID"/>			<xs:enumeration value="LINE_DASH"/>			<xs:enumeration value="LINE_DOT"/>			<xs:enumeration value="LINE_DASHDOT"/>			<xs:enumeration value="LINE_DASHDOTDOT"/>			<xs:enumeration value="LINE_CUSTOM"/>		</xs:restriction>	</xs:simpleType>	<xs:complexType name="RecordPropertiesType">		<xs:sequence>			<xs:element name="Measurement" type="MeasurementType"/>			<xs:element name="DisplayProperties" minOccurs="0">				<xs:complexType>					<xs:sequence>						<xs:element name="isDisplayable" type="xs:boolean" minOccurs="0"/>						<xs:element name="isVisible" type="xs:boolean" minOccurs="0"/>						<xs:element name="maxValue" type="xs:integer" minOccurs="0"/>						<xs:element name="minValue" type="xs:integer" minOccurs="0"/>						<xs:element name="defMaxValue" type="xs:double" minOccurs="0"/>						<xs:element name="defMinValue" type="xs:double" minOccurs="0"/>						<xs:element name="isPositionLeft" type="xs:boolean" minOccurs="0"/>						<xs:element name="color" type="ColorType" minOccurs="0"/>						<xs:element name="lineWidth" type="xs:integer" minOccurs="0"/>						<xs:element name="lineStyle" type="line_style_type" minOccurs="0"/>						<xs:element name="isRoundOut" type="xs:boolean" minOccurs="0"/>						<xs:element name="isStartpointZero" type="xs:boolean" minOccurs="0"/>						<xs:element name="isStartEndDefined" type="xs:boolean" minOccurs="0"/>						<xs:element name="numberFormat" type="xs:integer" minOccurs="0"/>					</xs:sequence>				</xs:complexType>			</xs:element>		</xs:sequence>	</xs:complexType>	<xs:complexType name="RecordSetPropertiesType">		<xs:sequence>			<xs:element name="TimeStep_ms" type="xs:double"/>			<xs:element name="TimeGridType" type="xs:integer" minOccurs="0"/>			<xs:element name="TimeGridLineStyle" type="line_style_type" minOccurs="0"/>			<xs:element name="TimeGridColor" type="ColorType" minOccurs="0"/>			<xs:element name="HorizontalGridRecord" type="xs:string" minOccurs="0"/>			<xs:element name="HorizontalGridType" type="xs:integer" minOccurs="0"/>			<xs:element name="HorizontalGridLineStyle" type="line_style_type" minOccurs="0"/>			<xs:element name="HorizontalGridColor" type="ColorType" minOccurs="0"/>		</xs:sequence>	</xs:complexType></xs:schema>

=== gitGNU/gnu_dataexplorer/DataExplorer/src/resource/DataExplorer_Sample.xml
<?xml version="1.0" encoding="UTF-8"?><DataExplorerFileFormat xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DataExplorerFileFormat_V02.xsd">	<VersionStamp>String</VersionStamp>	<CreationStamp>2010-01-01T09:00:00</CreationStamp>	<FileComment>String</FileComment>	<DeviceName>String</DeviceName>	<NumberOfRecordSets>1</NumberOfRecordSets>	<ObjectKey>String</ObjectKey>	<RecordSetDescription>		<RecordSetName>String</RecordSetName>		<Channel_Configuration/>		<RecordSetComment>String</RecordSetComment>		<RecordSetProperties>			<TimeStep_ms>3.141593E0</TimeStep_ms>			<TimeGridType>-0</TimeGridType>			<TimeGridLineStyle>LINE_SOLID</TimeGridLineStyle>			<TimeGridColor>				<Red>-0</Red>				<Green>-0</Green>				<Blue>-0</Blue>			</TimeGridColor>			<HorizontalGridRecord>String</HorizontalGridRecord>			<HorizontalGridType>-0</HorizontalGridType>			<HorizontalGridLineStyle>LINE_SOLID</HorizontalGridLineStyle>			<HorizontalGridColor>				<Red>-0</Red>				<Green>-0</Green>				<Blue>-0</Blue>			</HorizontalGridColor>		</RecordSetProperties>		<RecordProperties>			<Measurement>				<name>String</name>				<symbol>String</symbol>				<unit>String</unit>				<active>true</active>				<Property type="Integer" description="String" value="Text" name="String"/>				<Property type="Integer" description="String" value="Text" name="String"/>			</Measurement>			<DisplayProperties>				<isDisplayable>true</isDisplayable>				<isVisible>true</isVisible>				<maxValue>-0</maxValue>				<minValue>-0</minValue>				<defMaxValue>3.141593E0</defMaxValue>				<defMinValue>3.141593E0</defMinValue>				<isPositionLeft>true</isPositionLeft>				<color>					<Red>-0</Red>					<Green>-0</Green>					<Blue>-0</Blue>				</color>				<lineWidth>-0</lineWidth>				<lineStyle>LINE_SOLID</lineStyle>				<isRoundOut>true</isRoundOut>				<isStartpointZero>true</isStartpointZero>				<isStartEndDefined>true</isStartEndDefined>				<numberFormat>-0</numberFormat>			</DisplayProperties>		</RecordProperties>		<RecordDataSize>2147483647</RecordDataSize>		<RecordDataPointer>2147483647</RecordDataPointer>	</RecordSetDescription>	<RecordSetDataPoints>		<RecordDataArray>41394644363445313243</RecordDataArray>	</RecordSetDataPoints></DataExplorerFileFormat>
