=== gitGNU/gnu_dataexplorer/DataExplorer/src/resource/DeviceProperties_V16.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- *************************************************************************************  	This file is part of GNU DataExplorer.    GNU DataExplorer is free software: you can redistribute it and/or modify    it under the terms of the GNU General Public License as published by    the Free Software Foundation, either version 3 of the License, or    (at your option) any later version.    GNU DataExplorer is distributed in the hope that it will be useful,    but WITHOUT ANY WARRANTY; without even the implied warranty of    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    GNU General Public License for more details.    You should have received a copy of the GNU General Public License    along with GNU DataExplorer.  If not, see <http://www.gnu.org/licenses/>.        Copyright (c) 2008,2009,2010,2011,2012 Winfried Bruegmann************************************************************************************** --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">	<xs:element name="DeviceProperties" type="DevicePropertiesType">		<xs:annotation>			<xs:documentation>DataExplorer Properties</xs:documentation>		</xs:annotation>	</xs:element>	<xs:complexType name="DeviceType">		<xs:sequence>			<xs:element name="name">				<xs:complexType>					<xs:simpleContent>						<xs:extension base="xs:string">							<xs:attribute name="implementation" type="xs:string" use="optional">								<xs:annotation>									<xs:documentation>specify implementation class if different from name</xs:documentation>								</xs:annotation>							</xs:attribute>						</xs:extension>					</xs:simpleContent>				</xs:complexType>			</xs:element>			<xs:element name="manufacturer" type="xs:string"/>			<xs:element name="manufacturerURL" type="xs:anyURI"/>			<xs:element name="group" type="device_types"/>			<xs:element name="image" type="xs:anyURI"/>			<xs:element name="usage" type="xs:boolean"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="SerialPortType">		<xs:sequence>			<xs:element name="port" type="xs:string"/>			<xs:element name="baudeRate" type="baud_rate_types"/>			<xs:element name="dataBits" type="data_bits_types"/>			<xs:element name="stopBits" type="stop_bits_types"/>			<xs:element name="parity" type="parity_types"/>			<xs:element name="flowControlMode" type="flow_control_types"/>			<xs:element name="isRTS" type="xs:boolean"/>			<xs:element name="isDTR" type="xs:boolean"/>			<xs:sequence>				<xs:element name="TimeOut" type="TimeOutType" minOccurs="0"/>			</xs:sequence>		</xs:sequence>	</xs:complexType>	<xs:complexType name="DevicePropertiesType">		<xs:sequence>			<xs:element name="Device" type="DeviceType">				<xs:annotation>					<xs:documentation>Defines device specific global properties</xs:documentation>				</xs:annotation>			</xs:element>			<xs:element name="SerialPort" type="SerialPortType" minOccurs="0">				<xs:annotation>					<xs:documentation>Defines the serial port configuration</xs:documentation>				</xs:annotation>			</xs:element>			<xs:element name="TimeBase" type="TimeBaseType">				<xs:annotation>					<xs:documentation>Defines the time base used to display the data. A timeStep of -1 means time comes with data block and is not constant over an record set</xs:documentation>				</xs:annotation>			</xs:element>			<xs:element name="DataBlock" type="DataBlockType" minOccurs="0">				<xs:annotation>					<xs:documentation>This describes the data as to be interpreted as input. Nomally this is handeled by individual device plug-in</xs:documentation>				</xs:annotation>			</xs:element>			<xs:element name="State" type="StateType" minOccurs="0">				<xs:annotation>					<xs:documentation>Defines device processing states</xs:documentation>				</xs:annotation>			</xs:element>			<xs:element name="Channels">				<xs:complexType>					<xs:sequence>						<xs:element name="Channel" type="ChannelType" maxOccurs="unbounded">							<xs:annotation>								<xs:documentation>Defines output channels or configurations</xs:documentation>							</xs:annotation>						</xs:element>						<xs:element name="property" type="ChannelPropertyType" minOccurs="0" maxOccurs="unbounded"/>					</xs:sequence>					<xs:attribute name="lastUseOrdinal" type="xs:integer" use="optional"/>				</xs:complexType>			</xs:element>			<xs:element name="Desktop" type="DesktopType">				<xs:annotation>					<xs:documentation>Defines miscelanious visualisation properties of the application desktop</xs:documentation>				</xs:annotation>			</xs:element>		</xs:sequence>	</xs:complexType>	<xs:complexType name="TimeOutType">		<xs:sequence>			<xs:element name="RTOCharDelayTime" type="xs:integer"/>			<xs:element name="RTOExtraDelayTime" type="xs:integer"/>			<xs:element name="WTOCharDelayTime" type="xs:integer"/>			<xs:element name="WTOExtraDelayTime" type="xs:integer"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="DataBlockType">		<xs:sequence>			<xs:element name="format" maxOccurs="2">				<xs:annotation>					<xs:documentation>TEXT or BINARY</xs:documentation>				</xs:annotation>				<xs:complexType>					<xs:attribute name="inputType" type="input_types" use="required"/>					<xs:attribute name="formatType" type="format_types" use="required"/>					<xs:attribute name="size" type="xs:integer" use="required"/>				</xs:complexType>			</xs:element>			<xs:element name="checkSum" minOccurs="0">				<xs:complexType>					<xs:attribute name="format" type="format_types" default="BINARY"/>					<xs:attribute name="type" type="checkSum_types" default="XOR"/>				</xs:complexType>			</xs:element>			<xs:element name="timeUnit" type="time_unit_types" default="msec" minOccurs="0"/>			<xs:element name="separator" type="comma_separator_types" default="semicolon" minOccurs="0"/>			<xs:element name="leader" type="xs:string" default="$" minOccurs="0"/>			<xs:element name="trailer" type="xs:hexBinary" default="0D0A" minOccurs="0"/>			<xs:element name="preferredDataLocation" type="xs:string" minOccurs="0">				<xs:annotation>					<xs:appinfo/>					<xs:appinfo>preferred file location if raw data loaded from file</xs:appinfo>					<xs:appinfo/>					<xs:documentation/>				</xs:annotation>			</xs:element>			<xs:element name="preferredFileExtention" type="xs:string" default="*.csv" minOccurs="0">				<xs:annotation>					<xs:documentation>specify a file extention (*.abc) if the data file extension is diferent to *.csv</xs:documentation>				</xs:annotation>			</xs:element>		</xs:sequence>	</xs:complexType>	<xs:complexType name="TimeBaseType">		<xs:sequence>			<xs:element name="name" type="xs:string"/>			<xs:element name="symbol" type="xs:string"/>			<xs:element name="unit" type="xs:string"/>			<xs:element name="timeStep" type="xs:double">				<xs:annotation>					<xs:documentation>a negative value means variable time step, some devices allow editing, other edit by its configuration</xs:documentation>				</xs:annotation>			</xs:element>			<xs:element name="avarage_timeStep" type="xs:double" minOccurs="0">				<xs:annotation>					<xs:documentation>for backwards compatibility</xs:documentation>				</xs:annotation>			</xs:element>			<xs:element name="UTCdelta" type="xs:integer" minOccurs="0"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="MeasurementType">		<xs:sequence>			<xs:element name="name" type="xs:string"/>			<xs:element name="symbol" type="xs:string"/>			<xs:element name="unit" type="xs:string"/>			<xs:element name="active" type="xs:boolean" nillable="false" minOccurs="0">				<xs:annotation>					<xs:documentation>true can read data, false inactive, null -> calculation = true</xs:documentation>				</xs:annotation>			</xs:element>			<xs:element name="statistics" type="StatisticsType" minOccurs="0"/>			<xs:element name="property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="ChannelType">		<xs:sequence>			<xs:element name="Measurement" type="MeasurementType" maxOccurs="unbounded">				<xs:annotation>					<xs:documentation>Defines measurement capabilities, it might be calculations depending on measurements</xs:documentation>				</xs:annotation>			</xs:element>		</xs:sequence>		<xs:attribute name="name" type="xs:string" use="required"/>		<xs:attribute name="type" type="channel_types" use="required"/>	</xs:complexType>	<xs:complexType name="PropertyType">		<xs:attribute name="name" type="xs:string" use="required"/>		<xs:attribute name="value" use="required"/>		<xs:attribute name="type" type="data_types" use="required"/>		<xs:attribute name="description" type="xs:string"/>	</xs:complexType>	<xs:complexType name="ChannelPropertyType">		<xs:attribute name="name" type="channel_property_types" use="required"/>		<xs:attribute name="value" use="optional"/>		<xs:attribute name="type" type="data_types" use="required"/>		<xs:attribute name="description" type="xs:string"/>	</xs:complexType>	<xs:complexType name="DesktopPropertyType">		<xs:attribute name="name" type="desktop_property_types" use="required"/>		<xs:attribute name="value" type="xs:boolean" use="required"/>		<xs:attribute name="description" type="xs:string"/>		<xs:attribute name="target_reference_ordinal" type="xs:integer"/>	</xs:complexType>	<xs:complexType name="DesktopType">		<xs:sequence>			<xs:element name="property" type="DesktopPropertyType" minOccurs="4" maxOccurs="6"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="StatisticsType">		<xs:sequence>			<xs:element name="trigger" type="TriggerType" minOccurs="0"/>		</xs:sequence>		<xs:attribute name="min" type="xs:boolean" use="required"/>		<xs:attribute name="max" type="xs:boolean" use="required"/>		<xs:attribute name="avg" type="xs:boolean" use="required"/>		<xs:attribute name="sigma" type="xs:boolean" use="required"/>		<xs:attribute name="triggerRefOrdinal" type="xs:integer">			<xs:annotation>				<xs:documentation>references the measurement ordinal where trigger level is set in case of trigger is defined (0=VoltageReceiver;1=Voltage,2=Current, ...)</xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="sumByTriggerRefOrdinal" type="xs:integer">			<xs:annotation>				<xs:documentation>calculates sum of values where trigger level becomes active at referenced triggered measurement ordinal</xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="sumTriggerText" type="xs:string">			<xs:annotation>				<xs:documentation>this is the text displayed in front of sum value in case of trigger is defined</xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="countByTrigger" type="xs:boolean">			<xs:annotation>				<xs:documentation>counts the number of events trigger level becomes active  at specified trigger type </xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="countTriggerText" type="xs:string">			<xs:annotation>				<xs:documentation>text displayed in front of count value in case of trigger is defined</xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="comment" type="xs:string">			<xs:annotation>				<xs:documentation>trigger related comment in case of trigger is defined</xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="sumTriggerTimeText" type="xs:string">			<xs:annotation>				<xs:documentation>text displayed in front of the time sum value in case of trigger is defined displayed at time row</xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="ratioRefOrdinal" type="xs:integer">			<xs:annotation>				<xs:documentation>measurement ordinal to calculate the ratio of referenced avg or max value to sumByTriggerRefOrdinal</xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="ratioText" type="xs:string">			<xs:annotation>				<xs:documentation>text displayed in front of the calculated ratio case of resolvable dependencyes</xs:documentation>			</xs:annotation>		</xs:attribute>	</xs:complexType>	<xs:complexType name="TriggerType">		<xs:attribute name="level" type="xs:integer" use="required">			<xs:annotation>				<xs:documentation>describes the value level where statistics calculation is active (4000 == 4A)</xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="isGreater" type="xs:boolean" use="required">			<xs:annotation>				<xs:documentation>true means all values above trigger level will be counted</xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="minTimeSec" type="xs:integer" use="required">			<xs:annotation>				<xs:documentation>minimum time length in seconds of trigger range to filter short time periods</xs:documentation>			</xs:annotation>		</xs:attribute>		<xs:attribute name="comment" type="xs:string">			<xs:annotation>				<xs:documentation>trigger related comment</xs:documentation>			</xs:annotation>		</xs:attribute>	</xs:complexType>	<xs:complexType name="StateType">		<xs:sequence>			<xs:element name="property" type="PropertyType" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:simpleType name="data_types">		<xs:restriction base="xs:string">			<xs:enumeration value="Integer"/>			<xs:enumeration value="Double"/>			<xs:enumeration value="Boolean"/>			<xs:enumeration value="String"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="comma_separator_types">		<xs:restriction base="xs:string">			<xs:enumeration value="semicolon"/>			<xs:enumeration value="comma"/>			<xs:enumeration value="colon"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="decimal_separator_types">		<xs:restriction base="xs:string">			<xs:enumeration value="dot"/>			<xs:enumeration value="comma"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="device_types">		<xs:restriction base="xs:string">			<xs:enumeration value="logger"/>			<xs:enumeration value="charger"/>			<xs:enumeration value="multimeter"/>			<xs:enumeration value="variometer"/>			<xs:enumeration value="flightrecorder"/>			<xs:enumeration value="balancer"/>			<xs:enumeration value="current-sink"/>			<xs:enumeration value="receiver"/>			<xs:enumeration value="global-positioning-system"/>			<xs:enumeration value="power-supply"/>			<xs:enumeration value="control-unit"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="channel_types">		<xs:restriction base="xs:string">			<xs:enumeration value="TYPE_OUTLET"/>			<xs:enumeration value="TYPE_CONFIG"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="flow_control_types">		<xs:restriction base="xs:string">			<xs:enumeration value="FLOWCONTROL_NONE"/>			<xs:enumeration value="FLOWCONTROL_XON_XOFF"/>			<xs:enumeration value="FLOWCONTROL_HARDWARE"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="data_bits_types">		<xs:restriction base="xs:string">			<xs:enumeration value="DATABITS_5"/>			<xs:enumeration value="DATABITS_6"/>			<xs:enumeration value="DATABITS_7"/>			<xs:enumeration value="DATABITS_8"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="stop_bits_types">		<xs:restriction base="xs:string">			<xs:enumeration value="STOPBITS_1"/>			<xs:enumeration value="STOPBITS_2"/>			<xs:enumeration value="STOPBITS_1_5"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="parity_types">		<xs:restriction base="xs:string">			<xs:enumeration value="PARITY_NONE"/>			<xs:enumeration value="PARITY_ODD"/>			<xs:enumeration value="PARITY_EVEN"/>			<xs:enumeration value="PARITY_MARK"/>			<xs:enumeration value="PARITY_SPACE"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="checkSum_types">		<xs:restriction base="xs:string">			<xs:enumeration value="XOR"/>			<xs:enumeration value="ADD"/>			<xs:enumeration value="OR"/>			<xs:enumeration value="AND"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="format_types">		<xs:restriction base="xs:string">			<xs:enumeration value="BYTE"/>			<xs:enumeration value="VALUE"/>			<xs:enumeration value="BINARY"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="input_types">		<xs:restriction base="xs:string">			<xs:enumeration value="FILE_IO"/>			<xs:enumeration value="SERIAL_IO"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="line_ending_types">		<xs:restriction base="xs:string">			<xs:enumeration value="crlf"/>			<xs:enumeration value="cr"/>			<xs:enumeration value="lf"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="baud_rate_types">		<xs:restriction base="xs:integer">			<xs:enumeration value="2400"/>			<xs:enumeration value="4800"/>			<xs:enumeration value="7200"/>			<xs:enumeration value="9600"/>			<xs:enumeration value="14400"/>			<xs:enumeration value="19200"/>			<xs:enumeration value="28800"/>			<xs:enumeration value="38400"/>			<xs:enumeration value="57600"/>			<xs:enumeration value="115200"/>			<xs:enumeration value="128000"/>			<xs:enumeration value="256000"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="measurement_property_types">		<xs:restriction base="xs:string">			<xs:enumeration value="offset"/>			<xs:enumeration value="factor"/>			<xs:enumeration value="reduction"/>			<xs:enumeration value="do_subtract_first"/>			<xs:enumeration value="do_subtract_last"/>			<xs:enumeration value="regression_type"/>			<xs:enumeration value="regression_type_curve"/>			<xs:enumeration value="regression_type_linear"/>			<xs:enumeration value="regression_interval_sec"/>			<xs:enumeration value="number_cells"/>			<xs:enumeration value="prop_n100W"/>			<xs:enumeration value="is_invert_current"/>			<xs:enumeration value="number_motor"/>			<xs:enumeration value="revolution_factor"/>			<xs:enumeration value="scale_sync_ref_ordinal"/>			<xs:enumeration value="google_earth_velocity_avg_limit_factor"/>			<xs:enumeration value="google_earth_velocity_lower_limit"/>			<xs:enumeration value="google_earth_velocity_upper_limit"/>			<xs:enumeration value="google_earth_within_limits_color"/>			<xs:enumeration value="google_earth_lower_limit_color"/>			<xs:enumeration value="google_earth_upper_limit_color"/>			<xs:enumeration value="filter_factor"/>			<xs:enumeration value="none_specified"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="channel_property_types">		<xs:restriction base="xs:string">			<xs:enumeration value="enable_filter"/>			<xs:enumeration value="none_specified"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="time_unit_types">		<xs:restriction base="xs:string">			<xs:enumeration value="msec"/>			<xs:enumeration value="sec"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="desktop_property_types">		<xs:restriction base="xs:string">			<xs:enumeration value="table_tab"/>			<xs:enumeration value="digital_tab"/>			<xs:enumeration value="analog_tab"/>			<xs:enumeration value="voltage_per_cell_tab"/>			<xs:enumeration value="utility_garphics_tab"/>			<xs:enumeration value="utility_device_tab"/>		</xs:restriction>	</xs:simpleType></xs:schema>

=== gitGNU/gnu_dataexplorer/Picolario/src/resource/de/Picolario.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><DeviceProperties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DeviceProperties_V16.xsd">	<Device>		<name>Picolario</name>		<manufacturer>Renschler</manufacturer>		<manufacturerURL>http://www.renschler.de</manufacturerURL>		<group>logger</group>		<image>Picolario.jpg</image>		<usage>false</usage>	</Device>	<SerialPort>		<port>-</port>		<baudeRate>38400</baudeRate>		<dataBits>DATABITS_8</dataBits>		<stopBits>STOPBITS_1</stopBits>		<parity>PARITY_NONE</parity>		<flowControlMode>FLOWCONTROL_NONE</flowControlMode>		<isRTS>true</isRTS>		<isDTR>false</isDTR>	</SerialPort>	<TimeBase>		<name>Zeit</name>		<symbol>t</symbol>		<unit>msec</unit>		<timeStep>50</timeStep>	</TimeBase>    <DataBlock>        <format inputType="SERIAL_IO" formatType="BYTE" size="-31"/>		<checkSum type="XOR" format="BINARY"/>    </DataBlock>    <Channels>		<Channel type="TYPE_CONFIG" name="Thermik">			<Measurement>				<name>Spannung</name>				<symbol>U</symbol>				<unit>V</unit>				<active>true</active>				<statistics sigma="true" avg="true" max="true" min="true"/>				<property description="Spannungsoffset" type="Double" value="2.5" name="offset"/>				<property description="Messwertreduktion" type="Double" value="45" name="reduction"/>				<property description="Spannungsfaktor" type="Double" value="0.0532" name="factor"/>			</Measurement>			<Measurement>				<name>Höhe</name>				<symbol>h</symbol>				<unit>m</unit>				<active>true</active>				<statistics sigma="false" avg="true" max="true" min="true"/>				<property description="Höhenwertberechnung von Feet in Meter  (1852 / 6076)" type="Double" value="0.304806" name="factor"/>				<property description="Höhenwerte nicht anpassen" type="Boolean" value="false" name="do_no_adaption"/>				<property description="ersten Höhenwert von den Restlichen abziehen" type="Boolean" value="true" name="do_subtract_first"/>				<property description="letzten Höhenwert von den Restlichen abziehen" type="Boolean" value="false" name="do_subtract_last"/>				<property description="Offset von Höhenwerten abziehen" type="Boolean" value="false" name="do_offset_height"/>				<property description="Höhenoffsetwert" type="Double" value="0.0" name="offset"/>			</Measurement>			<Measurement>				<name>Steigen</name>				<symbol>V</symbol>				<unit>m/s</unit>				<statistics sigma="false" avg="true" max="true" min="true"/>				<property description="Zeit in Sekunden über die die regression durchgeführt wird" type="Integer" value="10" name="regression_interval_sec"/>				<property description="Regressionsrechnungsart" type="String" value="regression_type_curve" name="regression_type"/>			</Measurement>		</Channel>		<Channel type="TYPE_CONFIG" name="Motor">			<Measurement>				<name>Spannung</name>				<symbol>U</symbol>				<unit>V</unit>				<active>true</active>				<statistics sigma="true" avg="true" max="true" min="true"/>				<property description="Spannungsoffset" type="Double" value="2.5" name="offset"/>				<property description="Messwertreduktion" type="Double" value="45" name="reduction"/>				<property description="Spannungsfaktor" type="Double" value="0.0532" name="factor"/>			</Measurement>			<Measurement>				<name>Höhe</name>				<symbol>H</symbol>				<unit>m</unit>				<active>true</active>				<statistics countTriggerText="Ermittelt im Steigungstriggerbereich" sumTriggerText="Summe Motorhöhe" sumByTriggerRefOrdinal="2" sigma="false" avg="false" max="true" min="true"/>				<property description="Höhenwertberechnung von Feet in Meter  (1852 / 6076)" type="Double" value="0.304806" name="factor"/>				<property description="Höhenwerte nicht anpassen" type="Boolean" value="false" name="do_no_adaption"/>				<property description="ersten Höhenwert von den Restlichen abziehen" type="Boolean" value="false" name="do_subtract_first"/>				<property description="letzten Höhenwert von den Restlichen abziehen" type="Boolean" value="true" name="subtract_last"/>				<property description="Offset von Höhenwerten abziehen" type="Boolean" value="false" name="do_offset_height"/>				<property description="Höhenoffsetwert" type="Double" value="0.0" name="offset"/>			</Measurement>			<Measurement>				<name>Steigen</name>				<symbol>V</symbol>				<unit>m/s</unit>				<statistics countTriggerText="Anzahl gewerteter Steigflüge" countByTrigger="true" sigma="true" avg="true" max="true" min="false" sumTriggerTimeText="~ Motorlaufzeit">					<trigger comment="Trigger: Steigrate &gt; 1 m/sec &gt; 15 sec" minTimeSec="15" isGreater="true" level="1000"/>				</statistics>				<property description="Zeit in Sekunden über die die regression durchgeführt wird" type="Integer" value="10" name="regression_interval_sec"/>				<property description="Regressionsrechnungsart" type="String" value="regression_type_curve" name="regression_type"/>			</Measurement>		</Channel>	</Channels>	<Desktop>		<property value="false" name="table_tab"/>		<property value="false" name="voltage_per_cell_tab"/>		<property value="false" name="analog_tab"/>		<property value="false" name="digital_tab"/>	</Desktop></DeviceProperties>

=== gitGNU/gnu_dataexplorer/Picolario/src/resource/en/Picolario.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><DeviceProperties xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DeviceProperties_V16.xsd">	<Device>		<name>Picolario</name>		<manufacturer>Renschler</manufacturer>		<manufacturerURL>http://www.renschler.de</manufacturerURL>		<group>logger</group>		<image>Picolario.jpg</image>		<usage>false</usage>	</Device>	<SerialPort>		<port>-</port>		<baudeRate>38400</baudeRate>		<dataBits>DATABITS_8</dataBits>		<stopBits>STOPBITS_1</stopBits>		<parity>PARITY_NONE</parity>		<flowControlMode>FLOWCONTROL_NONE</flowControlMode>		<isRTS>true</isRTS>		<isDTR>false</isDTR>	</SerialPort>	<TimeBase>		<name>Time</name>		<symbol>t</symbol>		<unit>msec</unit>		<timeStep>50</timeStep>	</TimeBase>    <DataBlock>        <format inputType="SERIAL_IO" formatType="BYTE" size="-31"/>		<checkSum type="XOR" format="BINARY"/>    </DataBlock>    <Channels>		<Channel type="TYPE_CONFIG" name="Thermal">			<Measurement>				<name>Voltage</name>				<symbol>U</symbol>				<unit>V</unit>				<active>true</active>				<statistics sigma="true" avg="true" max="true" min="true"/>				<property description="Voltage offset" type="Double" value="2.5" name="offset"/>				<property description="Value reduction" type="Double" value="45" name="reduction"/>				<property description="Voltage factor" type="Double" value="0.0532" name="factor"/>			</Measurement>			<Measurement>				<name>Height</name>				<symbol>H</symbol>				<unit>m</unit>				<active>true</active>				<statistics sigma="false" avg="true" max="true" min="true"/>				<property description="Height calculation Feet to Meter  (1852 / 6076)" type="Double" value="0.304806" name="factor"/>				<property description="Do not adapt height values" type="Boolean" value="false" name="do_no_adaption"/>				<property description="Subtract first height value from subsequent" type="Boolean" value="true" name="do_subtract_first"/>				<property description="Subtract last height value from preceding" type="Boolean" value="false" name="do_subtract_last"/>				<property description="Subtract offset from height values" type="Boolean" value="false" name="do_offset_height"/>				<property description="Height offset" type="Double" value="0.0" name="offset"/>			</Measurement>			<Measurement>				<name>Climb</name>				<symbol>Vc</symbol>				<unit>m/sec</unit>				<statistics sigma="false" avg="true" max="true" min="true"/>				<property description="Zeit in Sekunden �ie die regression durchgef�ird" type="Integer" value="10" name="regression_interval_sec"/>				<property description="Regression calculation type" type="String" value="regression_type_curve" name="regression_type"/>			</Measurement>		</Channel>		<Channel type="TYPE_CONFIG" name="Motor">			<Measurement>				<name>Voltage</name>				<symbol>U</symbol>				<unit>V</unit>				<active>true</active>				<statistics sigma="true" avg="true" max="true" min="true"/>				<property description="Voltage offset" type="Double" value="2.5" name="offset"/>				<property description="Value reduction" type="Double" value="45" name="reduction"/>				<property description="Voltage factor" type="Double" value="0.0532" name="factor"/>			</Measurement>			<Measurement>				<name>Height</name>				<symbol>H</symbol>				<unit>m</unit>				<active>true</active>				<statistics countTriggerText="Calculated within slope trigger ranges" sumTriggerText="Sum motor climb height" sumByTriggerRefOrdinal="2" sigma="false" avg="false" max="true" min="true"/>				<property description="Height calculation Feet to Meter  (1852 / 6076)" type="Double" value="0.304806" name="factor"/>				<property description="Do not adapt height values" type="Boolean" value="false" name="do_no_adaption"/>				<property description="Subtract first height value from subsequent" type="Boolean" value="false" name="do_subtract_first"/>				<property description="Subtract last height value from preceding" type="Boolean" value="true" name="subtract_last"/>				<property description="Subtract offset from height values" type="Boolean" value="false" name="do_offset_height"/>				<property description="Height offset" type="Double" value="0.0" name="offset"/>			</Measurement>			<Measurement>				<name>Climb</name>				<symbol>Vc</symbol>				<unit>m/sec</unit>				<statistics countTriggerText="Number voted climbs" countByTrigger="true" sigma="true" avg="true" max="true" min="false" sumTriggerTimeText="~ motor run time">					<trigger comment="Trigger: Slope &gt; 1 m/sec &gt; 15 sec" minTimeSec="15" isGreater="true" level="1000"/>				</statistics>				<property description="Zeit in Sekunden �ie die regression durchgef�ird" type="Integer" value="10" name="regression_interval_sec"/>				<property description="Regression calculation type" type="String" value="regression_type_curve" name="regression_type"/>			</Measurement>		</Channel>	</Channels>	<Desktop>		<property value="false" name="table_tab"/>		<property value="false" name="voltage_per_cell_tab"/>		<property value="false" name="analog_tab"/>		<property value="false" name="digital_tab"/>	</Desktop></DeviceProperties>
